Repository cse110-sp21-group10/cse110-sp21-group10, pull requests merged in 2021-05, with the labels that each got.

#18 remove trailing whitespaces to test codefactor
  .github/workflows/auto-label-merge.yml
Labels: Approved

#14 Configuring the Linter
  .github/workflows/linter.yml
  README.md
Labels: Approved

#17 Basic HTML skeleton for yearly log
  source/HTML/yearly.html
Labels: Approved, Team 3

#10 Added HTML skeleton to monthly log
  source/HTML/monthly.html
Labels: Approved, Team 1

#15 Basic HTML skeleton for log templates and sidebar added
  source/HTML/sidebar.html
  source/HTML/template.html
Labels: Approved, Team 4

#19 Working on extracting the auto-label-merge action to an external script
  .github/workflows/auto-label-merge.yml
  .github/workflows/script.ps1
  .github/workflows/teams.json
Labels: T1 approval, T2 approval, T3 approval, T4 approval

#26 Making the spa pt.1
  source/HTML/daily.html
  source/style/style.css
Labels: T1 approval, T3 approval, T4 approval, Team 2

#27 Styled pages and buttons
  source/HTML/daily.html
  source/style/style.css
Labels: T2 approval, T4 approval, Team 1
