Repository cse110-sp21-group10/cse110-sp21-group10, pull requests merged in 2021-06, with the labels that each got.

#65 Bug fixes: History Navigation
  source/scripts/script.js
Labels: T1 approval, T2 approval, T3 approval

#64 Bullet element - bullet type selection
  source/HTML/log.html
  source/classes/bullet.js
  source/classes/monthly-log.js
  source/classes/yearly-log.js
  source/scripts/script.js
  source/style/style.css
Labels: T1 approval, T2 approval, T4 approval

#61 Labelling
  source/HTML/log.html
  source/classes/bullet.js
  source/classes/daily-log.js
  source/classes/monthly-log.js
  source/scripts/script.js
  source/style/style.css
Labels: T1 approval, T3 approval, Team 4

#66 Refactoring: Tooltips on hover
  source/HTML/log.html
  source/classes/bullet.js
Labels: T1 approval, T2 approval, T3 approval

#67 Input optimization (4/4): Enter, Up, Down, and Backspace
  source/classes/bullet.js
  source/classes/daily-log.js
Labels: T1 approval, T2 approval, T3 approval

#68 Styling Daily-Log 1/2
  source/style/style.css
Labels: T1 approval, T3 approval, T4 approval

#70 update Database for style object storage
  source/classes/database.js
Labels: T1 approval, T2 approval, T4 approval

#69 Yearly element styling
  source/classes/yearly-log.js
  source/scripts/script.js
  source/style/style.css
Labels: T1 approval, T3 approval, T4 approval

#71 History navigation bug fixes 2.0
  source/scripts/script.js
Labels: T1 approval, T2 approval, T3 approval, Team 3, Team 4

#74 Data Persistence (2/2) : User font and theme preferences saves/loads
  source/HTML/log.html
  source/classes/bullet.js
  source/scripts/index.js
  source/scripts/script.js
  source/style/style.css
Labels: T1 approval, T2 approval, T3 approval

#73 Unit testing and Most End to End Tests Implemented
  .gitignore
  babel.config.js
  package-lock.json
  package.json
  specs/testing/Database-Coverage.png
  specs/testing/IDConverter-Coverage.png
  specs/testing/spa-test.png
  specs/testing/testing.md
  tests/IDConverter.test.js
  tests/database.test.js
  tests/spa.test.js
Labels: T2 approval, T3 approval, T4 approval, Team 1

#76 Smol improvement: calendar write current month in red
  source/classes/yearly-log.js
  source/scripts/script.js
Labels: T1 approval, T2 approval, T3 approval

#72 Got automated testing into GH Actions
  .github/workflows/auto-test.yml
  package-lock.json
  package.json
  tests/spa.test.js
Labels: T1 approval, T2 approval, T3 approval

#75 Index menu -- Themes pt.1
  source/HTML/log.html
  source/assets/icons/01d_d.png
  source/assets/icons/01n_d.png
  source/assets/icons/02d_d.png
  source/assets/icons/02n_d.png
  source/assets/icons/03d_d.png
  source/assets/icons/03n_d.png
  source/assets/icons/04d_d.png
  source/assets/icons/04n_d.png
  source/assets/icons/09d_d.png
  source/assets/icons/09n_d.png
  source/assets/icons/10d_d.png
  source/assets/icons/10n_d.png
  source/assets/icons/11d_d.png
  source/assets/icons/11n_d.png
  source/assets/icons/13d_d.png
  source/assets/icons/13n_d.png
  source/assets/icons/50d_d.png
  source/assets/icons/50n_d.png
  source/assets/icons/unknown_d.png
  source/classes/monthly-log.js
  source/scripts/index.js
  source/scripts/script.js
  source/style/style.css
Labels: T1 approval, T3 approval, T4 approval, Team 2

#77 Section Reordering
  source/classes/daily-log.js
Labels: T1 approval, T2 approval, T4 approval

#82 re-style the delete section button
  source/classes/daily-log.js
  source/style/style.css
Labels: T1 approval, T2 approval, T4 approval, Team 3

#79 Monthly element styling + zoomOut
  .eslintrc.yml
  package-lock.json
  package.json
  source/HTML/log.html
  source/assets/css/solarized-dark.css
  source/classes/bullet.js
  source/classes/daily-log.js
  source/classes/monthly-log.js
  source/scripts/script.js
  source/style/style.css
Labels: T1 approval, T3 approval, T4 approval

#84 Zooming animations!!!
  source/scripts/script.js
  source/style/style.css
Labels: T1 approval, T2 approval, T3 approval, Team 2

#83 fixed monthly buttons for themes
  source/classes/monthly-log.js
  source/style/style.css
Labels: T1 approval, T3 approval, T4 approval
